In [1]:
### 모듈 로딩
import torch

- Tensor생성 [2] torch.rand()

In [5]:
# 0<= ~<1 범위의 임의의 숫자 1개 추출 => rand(*size)
# rand(*size) : 가변인자 ==> 몇 차원일지 알 수 없음!
torch.manual_seed(1)

dataTS1=torch.rand(3)     #1D 스칼라
dataTS2=torch.rand(2,3)   #2D 벡터
dataTS3=torch.rand(2,1,3) #3D 3차원

In [6]:
print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([0.7576, 0.2793, 0.4031])
tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])
tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]])


- Tensor 생성 [3] torch.randn()

In [8]:
# 정규분포를 따르게 음수가 나올 수 있다.
dataTS1=torch.randn(3)     #1D 스칼라
dataTS2=torch.randn(2,3)   #2D 벡터
dataTS3=torch.randn(2,1,3) #3D 3차원

In [9]:
print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([ 1.3240, -0.1005,  0.6443])
tensor([[ 0.5244,  1.0157,  0.2571],
        [-0.9013,  0.8138,  0.3871]])
tensor([[[0.5417, 0.6646, 0.3248]],

        [[0.0996, 0.5727, 1.1492]]])


- Tensor 생성[3] torch.randint()

In [10]:
torch.randint(1,5, (3,5))

tensor([[2, 1, 1, 2, 4],
        [4, 3, 2, 1, 3],
        [4, 4, 3, 2, 2]])

In [17]:
dataTS1=torch.randint(1,46,(6,))
dataTS1

tensor([44, 15, 38, 22, 25, 27])

In [14]:
# 2D
dataTS1=torch.randint(1,46,(4,6))
dataTS1

tensor([[28,  3,  3,  8, 24, 24],
        [34, 17, 32,  7, 11,  6],
        [43, 26, 29, 41, 36, 25],
        [20, 18, 16, 11, 24, 31]])