### Tesor의 모양/형태/shape 변경과 View Tensor

In [80]:
### 모듈 로딩
import torch
import numpy as np

In [81]:
## 텐서 생성
dataTS=torch.arange(1, 21)
print(dataTS, dataTS.ndim, dataTS.stride(), sep='\n')
print(f'is_contiguous() : {dataTS.is_contiguous()}')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)
is_contiguous() : True


In [82]:
print(dataTS.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [83]:
# 1D => 2D 형태/모양/shape 변경
dataTS2=dataTS.reshape((-1, 5))
print(dataTS2, dataTS2.ndim, dataTS2.stride(), sep='\n')
print(f'is_contiguous() : {dataTS2.is_contiguous()}')

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
is_contiguous() : True


In [84]:
print(dataTS2.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [85]:
#dataTS2[0][0]=77

In [86]:
dataTS, dataTS2

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

In [87]:
dataTS22=dataTS2.reshape((-1, 2))
print(dataTS22, dataTS22.ndim, dataTS22.stride(), sep='\n')
print(f'is_contiguous() : {dataTS22.is_contiguous()}')

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
is_contiguous() : True


In [88]:
dataTS23= dataTS22.T
dataTS23.is_contiguous()

False

In [89]:
## 불연속적 ==> 연속적으로 저장되도록
dTS=dataTS23.contiguous()

### 전치를 하면 기존의 순서를 벗어난다

In [90]:
dataTS23.storage()

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [91]:
dTS.storage()

 1
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [92]:
dataTS.storage()

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]