In [1]:
import numpy as np

In [2]:
v_3 = np.array([1, 2, 3])
v_3_n= np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [3]:
v_3_u = v_3 /v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [4]:
np.linalg.norm(v_3_u)

1.0

# 벡터의 상등

In [5]:
a = np.arange(3, 5)
b = np.arange(3, 5)
np.array_equal(a, b)

True

In [6]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)
a_1 == b_1

True

In [7]:
c = np.arange(10,13)
d = np.arange(0 ,3)

In [8]:
np.sqrt(np.sum(np.square(c-d)))

17.320508075688775

In [9]:
np.linalg.norm(c-d)

17.320508075688775

In [10]:
A = np.array([[43], [44]])

In [11]:
type(A)

numpy.ndarray

In [12]:
A

array([[43],
       [44]])

In [13]:
A.dtype

dtype('int32')

In [14]:
A.ndim

2

In [15]:
A.shape

(2, 1)

# 행렬 랭크

### np.linalg.matrix_rank는 독립이 아닌 백터가 존재하는걸 의미함

In [16]:
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])
np.linalg.matrix_rank(c1)

2

In [17]:
np.linalg.det(c1)

0.0

In [18]:
c1[0] *2 - c1[1]

array([0, 0, 0])

In [19]:
c2 = np.array([[1,3,4], [1,8,5], [2,3,4]])
np.linalg.matrix_rank(c2)

3

In [20]:
np.linalg.det(c2)

-17.0

In [21]:
np.linalg.matrix_rank(c2.T)

3

# 행렬의 축 axis=0 수직 , axis=1 수평

In [22]:
A = np.array([[2,3], [4,5]])

In [23]:
A.sum()

14

In [24]:
A.sum(axis = 0)

array([6, 8])

In [25]:
A.sum(axis= 1)

array([5, 9])

In [26]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [27]:
c.ndim

3

In [28]:
c.shape

(2, 2, 2)

In [29]:
c[0]

array([[1, 2],
       [3, 4]])

In [30]:
c[1]

array([[5, 6],
       [7, 8]])

In [31]:
c.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [32]:
c.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [33]:
c.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

# 차원 확장 및 축소

In [34]:
x = np.array([1,2])
x

array([1, 2])

In [35]:
y = np.expand_dims(x, axis= 1)
y

array([[1],
       [2]])

In [36]:
z = np.expand_dims(x, axis=0)
z

array([[1, 2]])

In [37]:
# 차원 축소
x = np.array([[1, 4, 5], [4, 5, 6], [7, 8, 9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [39]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

# 정사각행렬

In [40]:
a = np.array([[1,2,3], [4,5,6], [7,8,8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [41]:
a.shape

(3, 3)

In [42]:
np.trace(a)

14

In [43]:
a.trace()

14

# 대각행렬

In [44]:
b = np.array([[1,0,0], [0,3,0], [0,0,5]])
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [45]:
b.diagonal()

array([1, 3, 5])

In [46]:
np.diagonal(b)

array([1, 3, 5])

# 삼각행렬

In [47]:
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# 하삼각행렬
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [49]:
b = np.arange(1, 10).reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
# 상삼각행렬
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

# 대칭행렬

In [51]:
x = np.array([[1,2,3], [2, 3,5], [3, 5,6]])
x

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [52]:
x.T

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [53]:
np.array_equal(x, x.T)

True

In [54]:
np.array_equiv(x, x.T)

True

# 치환행렬

In [55]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
b= np.eye(3, dtype='int')
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
np.dot(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
c = np.array([[0,1,0],[1,0,0],[0,0,1]])

In [59]:
np.dot(a,c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

# 직교행렬

In [60]:
from scipy.stats import ortho_group

In [65]:
x = ortho_group.rvs(3)
x

array([[-0.92373203, -0.32747378, -0.19869589],
       [-0.06068288, -0.38707103,  0.92005087],
       [-0.37820197,  0.8619379 ,  0.33767786]])

In [66]:
i3 = np.dot(x,x.T)
i3

array([[ 1.00000000e+00,  3.44293370e-17, -2.55575910e-17],
       [ 3.44293370e-17,  1.00000000e+00,  1.82796572e-17],
       [-2.55575910e-17,  1.82796572e-17,  1.00000000e+00]])

In [67]:
c = np.eye(3)
np.allclose(c, i3)

True

# 전치행렬

In [68]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [69]:
a.T

array([[1, 3],
       [2, 4]])

In [70]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [71]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [72]:
a = dir(np)

In [73]:
np.ufunc

numpy.ufunc

In [75]:
count = 0
for i in a :
    if i == "Tester" :
        continue
    if i in np.__dict__ and type(np.__dict__[i]) == np.ufunc :
        print(i, end=" ")
        count +=1
        if count % 5 ==0:
            print()

abs absolute add arccos arccosh 
arcsin arcsinh arctan arctan2 arctanh 
bitwise_and bitwise_not bitwise_or bitwise_xor cbrt 
ceil conj conjugate copysign cos 
cosh deg2rad degrees divide divmod 
equal exp exp2 expm1 fabs 
float_power floor floor_divide fmax fmin 
fmod frexp gcd greater greater_equal 
heaviside hypot invert isfinite isinf 
isnan isnat lcm ldexp left_shift 
less less_equal log log10 log1p 
log2 logaddexp logaddexp2 logical_and logical_not 
logical_or logical_xor matmul maximum minimum 
mod modf multiply negative nextafter 
not_equal positive power rad2deg radians 
reciprocal remainder right_shift rint sign 
signbit sin sinh spacing sqrt 
square subtract tan tanh true_divide 
trunc 

In [76]:
a = np.array([[2, 3, 4, 5], [8, 9, 0, 1]])


In [77]:
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [80]:
a[np.ix_([0,1], [2,3])]


array([[4, 5],
       [0, 1]])

In [79]:
np.ix_([0,1], [0,1])

(array([[0],
        [1]]),
 array([[0, 1]]))

In [81]:
a = np.reshape(np.arange(10), (2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
c = a[[1,1,1], np.newaxis]

In [87]:
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

# 백터의 덧셈

In [88]:
d= np.array([3,4])
e = np.array([5,6])

d +e

array([ 8, 10])

In [89]:
np.add(d,e)

array([ 8, 10])

In [90]:
f = np.array([1,2,3])

In [91]:
try :
    f + e
except Exception as ex :
    print(ex)

operands could not be broadcast together with shapes (3,) (2,) 


# 백터의 뺼셈

In [92]:
d = np.array([3,4])
e = np.array([5,6])

d -e

array([-2, -2])

In [93]:
np.subtract(d,e)

array([-2, -2])

In [94]:
d + (-e)

array([-2, -2])

In [95]:
np.add(d, np.negative(e))

array([-2, -2])

# 스칼라 곱셈

In [96]:
d = np.array([2,3])
3*d

array([6, 9])

In [97]:
np.array([3,3]) * d

array([6, 9])

In [98]:
np.multiply(3,d)

array([6, 9])

In [99]:
np.multiply(np.array([3,3]), d)

array([6, 9])

# 브로드 캐스팅
## - 차원이 다른 배열간의 계산을 할 때는 먼저 원소별 계산을 위해 동일한 shape을 구성합니다

In [100]:
x = np.arange(10).reshape( 2,5)

In [101]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
y =np.arange(5)

In [103]:
y

array([0, 1, 2, 3, 4])

In [104]:
z = np.broadcast(x, y)

In [105]:
z

In [106]:
type(z)

numpy.broadcast

In [107]:
z.shape, z.ndim

((2, 5), 2)

In [108]:
for i in z:
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [109]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [110]:
x2 = np.ones((2,3))

In [111]:
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [112]:
x1 = np.ones(3)
x1

array([1., 1., 1.])

In [113]:
x1.shape, x2.shape

((3,), (2, 3))

In [114]:
# 마지막 원소 개수 확인
x1.shape[0] == x2.shape[1]

True

In [115]:
# 차원을 추가함
x1 = x1[np.newaxis,]
x1.shape

(1, 3)

In [116]:
# 행을 하나 더 추가
x1 = np.vstack((x1[0],x1[0]))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [118]:
x1.shape == x2.shape

True

In [119]:
x1 +x2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [120]:
x = np.arange(1,4)
x

array([1, 2, 3])

In [121]:
x1 = x.reshape(1,3)
x1

array([[1, 2, 3]])

In [133]:
x.shape


(3,)

In [122]:
# 차원추가
x2 = x[np.newaxis,]
x2

array([[1, 2, 3]])

In [123]:
y = np.arange(1,4)
y

array([1, 2, 3])

In [124]:
y1 = y.reshape(3,1)

In [125]:
y1

array([[1],
       [2],
       [3]])

In [126]:
y2 = y[:, np.newaxis]

In [127]:
y2

array([[1],
       [2],
       [3]])

In [128]:
np.broadcast_arrays(x1, y1)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [129]:
x1 +y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# 벡터의 내적

In [134]:
a = np.array([3, 4])
b = np.array([5, 6])

In [135]:
a @ b

39

In [136]:
np.dot(a,b)

39

In [137]:
np.inner(a, b)

39

# 벡터의 외적

In [138]:
a = np.array([1,4])
b = np.array([3,6])
np.cross(a,b)

array(-6)

In [139]:
c = np.array([1, 4,3])

In [140]:
d= np.array([3,4,5])


In [141]:
np.cross(c,d)

array([ 8,  4, -8])

# 행렬식

In [142]:
a = np.array([[3,1], [2,2]])
np.linalg.det(a)

4.000000000000001

In [143]:
np.allclose(4.0, np.linalg.det(a))

True

In [145]:
b = np.array([[3,1,3],[2,2,3],[1,1,1]])
b

array([[3, 1, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [146]:
3*np.linalg.det(b[1:, 1:])

-3.0

In [147]:
np.linalg.det(b[1:, ::2])

-1.0

In [148]:
3*np.linalg.det(b[1:, :2])

0.0

In [149]:
np.linalg.det(b)

-2.0

In [150]:
-3 +1 +0

-2

In [151]:
a = np.array([[3,2], [6,4]])

In [152]:
np.linalg.det(a)

0.0

In [153]:
b=np.array([[1,2,3], [4,5,6], [3,2,4]])

In [154]:
np.linalg.det(b)

-9.000000000000002

In [155]:
bi = np.linalg.inv(b)

In [156]:
bb = np.dot(b, bi)

In [157]:
np.allclose(np.eye(3), bb)

True

# 역행렬의 교환법칙

In [158]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [159]:
ai = np.linalg.inv(a)

In [160]:
ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [161]:
x = np.dot(a, ai)

In [162]:
x

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [163]:
np.allclose(np.eye(2), x)

True

In [164]:
y =np.dot(ai, a)

In [165]:
y

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [166]:
np.allclose(np.eye(2), y)

True

In [167]:
np.allclose(x,y)

True

In [168]:
a = np.array([[1,2], [3,4]])

In [169]:
np.linalg.det(a)

-2.0000000000000004

In [170]:
b= np.array([[3,4],[1,2]])

In [171]:
np.linalg.det(b)

2.0000000000000004

In [172]:
ai = np.linalg.inv(a)

In [173]:
bi = np.linalg.inv(b)

In [174]:
ab = np.linalg.inv(np.dot(a,b))

In [175]:
ba = np.dot(bi,ai)

In [176]:
np.allclose(ab,ba)

True

# 배열의 형상 변경

In [179]:
x= np.arange(16)

In [180]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [181]:
x1 = x.reshape(2, 8)

In [182]:
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [183]:
try :
    x2 = x.reshape(4 ,5)
except Exception as e:
    print(e)

cannot reshape array of size 16 into shape (4,5)


In [184]:
y1 = x.reshape(4,-1)

In [185]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [186]:
a = np.arange(4)

In [187]:
a

array([0, 1, 2, 3])

In [188]:
np.resize(a, 8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [189]:
np.append(a ,a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [190]:
b =np.arange(4)

In [191]:
b.resize((4,4))

In [192]:
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [193]:
# 새로운 배열을 만들때 refcheck=False
c = np.arange(8)

In [194]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [195]:
c.resize(4, refcheck=False)

In [196]:
c

array([0, 1, 2, 3])

## Meshgrid 함수: 두 개의 배열을 가지고 확장된 두개의 다른 배열을 만듬

In [197]:
x = np.arange(3)

In [198]:
y= np.arange(4)

In [199]:
x_, y_ = np.meshgrid(x,y)

In [200]:
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [201]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [202]:
x_1 = x.reshape(1,-1)

In [203]:
np.concatenate([x_1, x_1, x_1, x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [204]:
y_1 = y.reshape(-1,1)

In [205]:
np.concatenate([y_1, y_1, y_1, y_1], axis=1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

# mgrid 함수 : 인자로 슬라이스 전달하면 두 개의 배열을 반환

In [206]:
np.arange(10, 30, 10)
np.arange(1,5)

array([1, 2, 3, 4])

In [207]:
np.broadcast_arrays(np.arange(10,30,10).reshape(2,1), np.arange(1,5).reshape(1,4))

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [208]:
a, b = np.mgrid[10:30:10, 1:5]

In [209]:
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [210]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [211]:
c, d = np.ogrid[10:30:10, 1:5]

In [212]:
c

array([[10],
       [20]])

In [213]:
d

array([[1, 2, 3, 4]])

In [214]:
e,f = np.broadcast_arrays(c,d)

In [215]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [216]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 차원 줄이기    np.squeeze 이용

In [217]:
x = np.array([[[0],[1],[2]]])

In [219]:
x

array([[[0],
        [1],
        [2]]])

In [220]:
x.shape

(1, 3, 1)

In [221]:
np.squeeze(x)

array([0, 1, 2])

In [222]:
np.squeeze( x, axis=0)

array([[0],
       [1],
       [2]])

In [223]:
np.squeeze( x, axis=2)


array([[0, 1, 2]])

In [224]:
a = np.linspace(1, 5, 5, dtype=np.int32)

In [225]:
a

array([1, 2, 3, 4, 5])

In [226]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [227]:
e = np.arange(4).reshape(2,2)

In [228]:
e

array([[0, 1],
       [2, 3]])

In [229]:
np.tile(e,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

# 배열 결합하기

In [230]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)

In [231]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [232]:
b = np.linspace(7, 13, 6, dtype=np.int32).reshape(2, 3)

In [233]:
b

array([[ 7,  8,  9],
       [10, 11, 13]])

# 열의 크기가 동일할 때 수직 결합

In [234]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]])

# 행의 크기가 동일할 때 수평결합

In [235]:

np.concatenate([a,b], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]])

# 배열 쌓기
## - stack,vstack, hstack 함수로 배열을 수직과 수평으로 쌓을 수 있다.

In [236]:
x = np.array([1,2,3])
y= np.array([4,5,6])
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [237]:
np.stack([x,y], axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [238]:
a = np.vstack([x,y])

In [239]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [240]:
np.vstack([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [241]:
np.stack([x,y], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [242]:
b = np.hstack([x,y])

In [243]:
b

array([1, 2, 3, 4, 5, 6])

In [244]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [245]:
b= np.vstack([a,a])

In [246]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [247]:
x,y = np.split(b,[2])

In [248]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [249]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [250]:
a = np.arange(6).reshape(2,3)

In [251]:
c = np.random.randn(2,3)

In [252]:
np.r_[a,c]

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 1.76475668,  0.10145483, -0.12647907],
       [ 1.07203756,  0.27746053,  1.00627395]])

In [253]:
np.c_[a,c]

array([[ 0.        ,  1.        ,  2.        ,  1.76475668,  0.10145483,
        -0.12647907],
       [ 3.        ,  4.        ,  5.        ,  1.07203756,  0.27746053,
         1.00627395]])